FROM ubuntu
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get -y install dotnet6

RUN apt update && apt install tzdata -y
RUN apt install nano -y

ENV TZ="Asia/Taipei"
# docker image build -f  Dockerfile_net6sdk -t net6sdk .



